"""add otp table

Revision ID: 0c0138f1db27
Revises: c1111acc3d3a
Create Date: 2026-01-16 14:41:21.770654
"""

from alembic import op
import sqlalchemy as sa

revision = "0c0138f1db27"
down_revision = 'c1111acc3d3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp_token', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_identifier'), 'otps', ['identifier'], unique=False)
    op.create_index(op.f('ix_otps_otp_token'), 'otps', ['otp_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otps_otp_token'), table_name='otps')
    op.drop_index(op.f('ix_otps_identifier'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
